<a href="https://colab.research.google.com/github/AndreSlavescu/Hardware_Implemented_Neural_Network/blob/main/MLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Imports and Setup

In [1]:
# download dependencies
!pip install tensorflow numpy pandas keras

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
# Imports
import numpy as np

from tensorflow.keras import optimizers
from keras import models
from keras import layers
from tensorflow.keras.utils import to_categorical

from sklearn import datasets
from sklearn.model_selection import train_test_split

# Load Data

## Find Dataset Here: 
https://www.kaggle.com/datasets/arshid/iris-flower-dataset?select=IRIS.csv

In [3]:
iris_dataset = datasets.load_iris()

X = iris_dataset.data
y = iris_dataset.target


for num in iris_dataset['data']:
  num *= 10

iris_dataset['data'] = iris_dataset['data'].astype(int)

In [4]:
iris_dataset

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

# Defining the Model

In [5]:
network = models.Sequential()
network.add(layers.Dense(3, activation='sigmoid', input_shape=(4,)))

# Compiling the Model

In [6]:
adam_optimizer = optimizers.Adam(learning_rate=0.1)

network.compile(optimizer=adam_optimizer,
                loss='categorical_crossentropy',
                metrics=['accuracy'])

# Separating Training and Testing Data

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

train_labels = to_categorical(y_train)
test_labels = to_categorical(y_test)


# Training the Model

In [19]:
try:
  network = models.load_model('/content/sample_data/mlp')
except:
  network.fit(X_train, train_labels, epochs=20, batch_size=1)

Epoch 1/20
120/120 [==============================] - 1s 2ms/step - loss: 1.8435 - accuracy: 0.9000
Epoch 2/20
120/120 [==============================] - 0s 2ms/step - loss: 2.8620 - accuracy: 0.8833
Epoch 3/20
120/120 [==============================] - 0s 2ms/step - loss: 0.8125 - accuracy: 0.9583
Epoch 4/20
120/120 [==============================] - 0s 2ms/step - loss: 1.1646 - accuracy: 0.9250
Epoch 5/20
120/120 [==============================] - 0s 2ms/step - loss: 5.6979 - accuracy: 0.8500
Epoch 6/20
120/120 [==============================] - 0s 2ms/step - loss: 1.9402 - accuracy: 0.8917
Epoch 7/20
120/120 [==============================] - 0s 2ms/step - loss: 1.8128 - accuracy: 0.9083
Epoch 8/20
120/120 [==============================] - 0s 2ms/step - loss: 3.0701 - accuracy: 0.8667
Epoch 9/20
120/120 [==============================] - 0s 2ms/step - loss: 0.4072 - accuracy: 0.9417
Epoch 10/20
120/120 [==============================] - 0s 2ms/step - loss: 1.3540 - accuracy: 0.9250

# Evaluating the Model with Test Data

In [24]:
test_loss, test_acc = network.evaluate(X_test, test_labels)

1/1 [==============================] - 0s 19ms/step - loss: 1.0212e-06 - accuracy: 1.0000


# Save the model

In [21]:
network.save('/content/sample_data/mlp')

INFO:tensorflow:Assets written to: /content/sample_data/mlp/assets


In [31]:
for layer in network.layers: print(layer.get_weights()[0].astype(int), layer.get_weights()[1].astype(int))

[[  2   2  -1]
 [  5   0  -4]
 [ -6  -1   3]
 [-11  -4   7]] [  4   9 -12]
